export const spells = [
  // WIZARD
  { class: 'Wizard', tier: 1, name: 'Alarm' },
  { class: 'Wizard', tier: 1, name: 'Burning Hands' },
  { class: 'Wizard', tier: 1, name: 'Charm Person' },
  { class: 'Wizard', tier: 1, name: 'Detect Magic' },
  { class: 'Wizard', tier: 1, name: 'Feather Fall' },
  { class: 'Wizard', tier: 1, name: 'Floating Disk' },
  { class: 'Wizard', tier: 1, name: 'Hold Portal' },
  { class: 'Wizard', tier: 1, name: 'Light' },
  { class: 'Wizard', tier: 1, name: 'Mage Armor' },
  { class: 'Wizard', tier: 1, name: 'Magic Missile' },
  { class: 'Wizard', tier: 1, name: 'Protection From Evil' },
  { class: 'Wizard', tier: 1, name: 'Sleep' },

  { class: 'Wizard', tier: 2, name: 'Acid Arrow' },
  { class: 'Wizard', tier: 2, name: 'Alter Self' },
  { class: 'Wizard', tier: 2, name: 'Detect Thoughts' },
  { class: 'Wizard', tier: 2, name: 'Fixed Object' },
  { class: 'Wizard', tier: 2, name: 'Hold Person' },
  { class: 'Wizard', tier: 2, name: 'Invisibility' },
  { class: 'Wizard', tier: 2, name: 'Knock' },
  { class: 'Wizard', tier: 2, name: 'Levitate' },
  { class: 'Wizard', tier: 2, name: 'Mirror Image' },
  { class: 'Wizard', tier: 2, name: 'Misty Step' },
  { class: 'Wizard', tier: 2, name: 'Silence' },
  { class: 'Wizard', tier: 2, name: 'Web' },

  { class: 'Wizard', tier: 3, name: 'Animate Dead' },
  { class: 'Wizard', tier: 3, name: 'Dispel Magic' },
  { class: 'Wizard', tier: 3, name: 'Fabricate' },
  { class: 'Wizard', tier: 3, name: 'Fireball' },
  { class: 'Wizard', tier: 3, name: 'Fly' },
  { class: 'Wizard', tier: 3, name: 'Gaseous Form' },
  { class: 'Wizard', tier: 3, name: 'Illusion' },
  { class: 'Wizard', tier: 3, name: 'Lightning Bolt' },
  { class: 'Wizard', tier: 3, name: 'Magic Circle' },
  { class: 'Wizard', tier: 3, name: 'Protection From Energy' },
  { class: 'Wizard', tier: 3, name: 'Sending' },
  { class: 'Wizard', tier: 3, name: 'Speak With Dead' },

  { class: 'Wizard', tier: 4, name: 'Arcane Eye' },
  { class: 'Wizard', tier: 4, name: 'Cloudkill' },
  { class: 'Wizard', tier: 4, name: 'Confusion' },
  { class: 'Wizard', tier: 4, name: 'Control Water' },
  { class: 'Wizard', tier: 4, name: 'Dimension Door' },
  { class: 'Wizard', tier: 4, name: 'Divination' },
  { class: 'Wizard', tier: 4, name: 'Passwall' },
  { class: 'Wizard', tier: 4, name: 'Polymorph' },
  { class: 'Wizard', tier: 4, name: 'Resilient Sphere' },
  { class: 'Wizard', tier: 4, name: 'Stoneskin' },
  { class: 'Wizard', tier: 4, name: 'Telekinesis' },
  { class: 'Wizard', tier: 4, name: 'Wall of Force' },

  { class: 'Wizard', tier: 5, name: 'Antimagic Shell' },
  { class: 'Wizard', tier: 5, name: 'Create Undead' },
  { class: 'Wizard', tier: 5, name: 'Disintegrate' },
  { class: 'Wizard', tier: 5, name: 'Hold Monster' },
  { class: 'Wizard', tier: 5, name: 'Plane Shift' },
  { class: 'Wizard', tier: 5, name: 'Power Word Kill' },
  { class: 'Wizard', tier: 5, name: 'Prismatic Orb' },
  { class: 'Wizard', tier: 5, name: 'Scrying' },
  { class: 'Wizard', tier: 5, name: 'Shapechange' },
  { class: 'Wizard', tier: 5, name: 'Summon Extraplanar' },
  { class: 'Wizard', tier: 5, name: 'Teleport' },
  { class: 'Wizard', tier: 5, name: 'Wish' },

  // PRIEST
  { class: 'Priest', tier: 1, name: 'Cure Wounds' },
  { class: 'Priest', tier: 1, name: 'Holy Weapon' },
  { class: 'Priest', tier: 1, name: 'Light' },
  { class: 'Priest', tier: 1, name: 'Protection From Evil' },
  { class: 'Priest', tier: 1, name: 'Shield of Faith' },
  { class: 'Priest', tier: 1, name: 'Turn Undead' },

  { class: 'Priest', tier: 2, name: 'Augury' },
  { class: 'Priest', tier: 2, name: 'Bless' },
  { class: 'Priest', tier: 2, name: 'Blind/Deafen' },
  { class: 'Priest', tier: 2, name: 'Cleansing Weapon' },
  { class: 'Priest', tier: 2, name: 'Smite' },
  { class: 'Priest', tier: 2, name: 'Zone of Truth' },

  { class: 'Priest', tier: 3, name: 'Command' },
  { class: 'Priest', tier: 3, name: 'Lay To Rest' },
  { class: 'Priest', tier: 3, name: 'Mass Cure' },
  { class: 'Priest', tier: 3, name: 'Rebuke Unholy' },
  { class: 'Priest', tier: 3, name: 'Restoration' },
  { class: 'Priest', tier: 3, name: 'Speak With Dead' },

  { class: 'Priest', tier: 4, name: 'Commune' },
  { class: 'Priest', tier: 4, name: 'Control Water' },
  { class: 'Priest', tier: 4, name: 'Flame Strike' },
  { class: 'Priest', tier: 4, name: 'Pillar of Salt' },
  { class: 'Priest', tier: 4, name: 'Regenerate' },
  { class: 'Priest', tier: 4, name: 'Wrath' },

  { class: 'Priest', tier: 5, name: 'Divine Vengeance' },
  { class: 'Priest', tier: 5, name: 'Dominion' },
  { class: 'Priest', tier: 5, name: 'Heal' },
  { class: 'Priest', tier: 5, name: 'Judgment' },
  { class: 'Priest', tier: 5, name: 'Plane Shift' },
  { class: 'Priest', tier: 5, name: 'Prophecy' }
];
